database:
  url: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  max_connections: 10

server:
  port: "8888"
  base_path: "/api/v1"
  timeout: 30
  max_clients: 100

logging:
  level: "debug"
  format: "text"
  output_file: "admin/log/log.log"


security:
  jwt_secret: "supersecretkey"
